// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArj4DmlrGPuO4bHkcoQMS3dJafCD2kfI8',
    appId: '1:671249252042:web:339bd5d02ab6b561ab3e33',
    messagingSenderId: '671249252042',
    projectId: 'abnt-play',
    authDomain: 'abnt-play.firebaseapp.com',
    storageBucket: 'abnt-play.appspot.com',
    measurementId: 'G-M2435277T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNqZSLxQc0g0qmPoJLEjIXp_Wc5lLO64',
    appId: '1:671249252042:android:74392653ab9dd305ab3e33',
    messagingSenderId: '671249252042',
    projectId: 'abnt-play',
    storageBucket: 'abnt-play.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3X5bNX02R80kPwUvNCJQLJXCSct1maJs',
    appId: '1:671249252042:ios:c9491ee7bfc264cdab3e33',
    messagingSenderId: '671249252042',
    projectId: 'abnt-play',
    storageBucket: 'abnt-play.appspot.com',
    iosClientId: '671249252042-jro6g5sg0vhgp6gvo3bcjqo9jf73imtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.abntplaybic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3X5bNX02R80kPwUvNCJQLJXCSct1maJs',
    appId: '1:671249252042:ios:c9491ee7bfc264cdab3e33',
    messagingSenderId: '671249252042',
    projectId: 'abnt-play',
    storageBucket: 'abnt-play.appspot.com',
    iosClientId: '671249252042-jro6g5sg0vhgp6gvo3bcjqo9jf73imtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.abntplaybic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArj4DmlrGPuO4bHkcoQMS3dJafCD2kfI8',
    appId: '1:671249252042:web:cc0e7bb09429d6b1ab3e33',
    messagingSenderId: '671249252042',
    projectId: 'abnt-play',
    authDomain: 'abnt-play.firebaseapp.com',
    storageBucket: 'abnt-play.appspot.com',
    measurementId: 'G-5CEP10F5T4',
  );

}